version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - cache:/app/cache
      - public:/app/public
      - yarn_cache:/usr/local/share/.cache/yarn/v4
    ports:
      - '12800:12800'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: 'yarn develop --host 0.0.0.0 --port 12800'

volumes:
  node_modules:
  cache:
  public:
  yarn_cache:
