version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - cache:/app/.cache
      - public:/app/public
      - yarn_cache:/usr/local/share/.cache/yarn/v4
    ports:
      - '25800:25800'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      HOST: '0.0.0.0'
      port: '25800'
    command: 'yarn develop'

volumes:
  node_modules:
  cache:
  public:
  yarn_cache:
